Project setup
DilsherB/bookstore pull request #3
Opened 2023-06-08 11:02 UTC by DilsherB

in this PR:
1. Following Components Created.
    a. Books
    b. BookAction
    c. BookDetail
    d. BookProgress
    e. Menu
    f. Categories
2. React-router-dom installed.
3. Basic setup of routers done.
4. No linter errors
5. git flow followed.

2023-06-08 11:07 UTC, topeogunleye reviewed
Hi @DilsherB, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that the README file that does not use the Microverse template. Please use the [Microverse template](https://github.com/microverseinc/readme-template).

- [ ] In the case of README consider not leaving out any of the sections in the [Microverse README](https://github.com/microverseinc/readme-template) template as it's a project requirement.

| professional Readme  | Your Readme that is not professional |
| ------------- | ------------- |
|  ![Recording 2023-02-14 at 12 52 20 (5)](https://user-images.githubusercontent.com/83360636/218715072-2b2d3a49-8219-4939-b350-45cc950f7f7a.gif)	  | <img width="668" alt="image" src="https://github.com/DilsherB/bookstore/assets/52934128/360128b7-dbce-43d6-bbe7-17194283ee5d"> |

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-08 11:47 UTC, uwadonat requested changes
## Hi @DilsherB,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Detailed pull request message ✔️
- Professional readme files ✔️
- Correct workflow was used ✔️
![almost](https://github.com/DilsherB/bookstore/assets/65860678/a664b391-d057-41f9-8884-698ad0fceb92)

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 11:47 UTC, uwadonat commented on src/components/Books.js
> +  );
Hello @DilsherB 
- [ ] As requested in the project requirements, let make sure below features are implemented:
- Contains individual book state, as well as a button to delete the book (the button wouldn't remove the books *yet*, this is just a placeholder for now)
- Contains a list to renders individual books
- Contains a form to create new books (with inputs for the title, the author of the book and a button to submit)
   the button wouldn't add the book *yet*, this is just a placeholder for now

2023-06-10 10:19 UTC, omarsalem7 approved these changes
Hi @DilsherB 😊, 
# STATUS: APPROVED! 🥇 💯 

<!--- ![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif) -->

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 11:08 UTC, merged